### ISSUE TITLE
I18n support?

### ISSUE THREAD

**Issue by johnfelipe** [bandinopla/skill-assessments-quizzes#1]

**Comment by bandinopla** [comment]
you mean for the UI?

**Comment by johnfelipe** [comment]
Yep
I want to translate to es, de and it if u put strings in Pot, yml, Json or
any file of that

**Comment by bandinopla** [comment]
ok, added this mechanic in the latest commit: https://github.com/bandinopla/skill-assessments-quizzes/commit/8011079dd93b9129541af75af97cfcd9d5076de9

read the docs to learn how to add the new translation files!

**Comment by bandinopla** [comment]
@all-contributors add @johnfelipe for ideas
