### ISSUE TITLE
Spring Framework Test - Q41 All answers marked as wrong

### ISSUE THREAD

**Issue by z1n0v1** [bandinopla/skill-assessments-quizzes#5]
![quizz-spring-Q41-all-answers-wrong](https://user-images.githubusercontent.com/98004928/185545866-415fbd71-5354-4e3f-96d6-ec80cb7c9703.jpg)

https://github.com/Ebazhanov/linkedin-skill-assessments-quizzes/blob/d0bb031a8bf86b72de764f1b57842f605a78d378/spring-framework/spring-framework-quiz.md?plain=1#L345

**Comment by bandinopla** [comment]
@all-contributors add @z1n0v1 for Bug reports
